# Generated by Django 3.0.3 on 2020-09-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyPersonUserEmail', models.EmailField(max_length=254)),
                ('valuePersonUserEmail', models.EmailField(max_length=254)),
                ('friendSince', models.DateTimeField()),
            ],
        ),
    ]
